title = "villalba.is"
baseURL = "/"
languageCode = "es"
theme = ["ananke"]
enableInlineShortcodes = true
#theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
resourceDir = "../resources"

DefaultContentLanguage = "es"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.es]
    title = "Ananke"
    weight = 1
    contentDir = "content/es"
    # languageDirection = 'rtl' for Right-To-Left languages
#  [languages.fr]
#    title = "Ananke Fr"
#    weight = 2
#    contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Wilson Villalba"
  favicon = "/favicons/favicon.ico"
  site_logo = "vvv.svg"
  description = "Litigios."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-blue"
  recent_posts_number = 6
  post_content_classes = "athelas"
  body_classes = "times"
  feature_image = "/images/cover.jpg"
  mainSections = ['posts', 'modelos']



[[params.ananke_socials]]
name = "telegram"
url = "https://t.me/cives.cfd"
